// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/command.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_44307652f2d29e97, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Command) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Credentials struct {
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_44307652f2d29e97, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_44307652f2d29e97, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "command.Command")
	proto.RegisterType((*Credentials)(nil), "command.Credentials")
	proto.RegisterType((*Token)(nil), "command.Token")
}

func init() { proto.RegisterFile("grpc/command.proto", fileDescriptor_44307652f2d29e97) }

var fileDescriptor_44307652f2d29e97 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0xdb, 0x6d, 0xeb, 0x08, 0x22, 0x43, 0x0f, 0x71, 0x45, 0x90, 0x3d, 0xf5, 0xe2,
	0xae, 0xd8, 0x6f, 0x60, 0xf1, 0xe0, 0x4d, 0x6a, 0x4f, 0xbd, 0xa5, 0xdd, 0x10, 0x83, 0xcd, 0x64,
	0xc9, 0x1f, 0xec, 0xc7, 0x97, 0x64, 0xdb, 0x5d, 0xa1, 0xb7, 0x79, 0xbf, 0x17, 0x32, 0x6f, 0x1e,
	0xa0, 0xb4, 0xed, 0xbe, 0xde, 0x1b, 0xad, 0x39, 0x35, 0x55, 0x6b, 0x8d, 0x37, 0x38, 0x3d, 0xc9,
	0x72, 0x09, 0xd3, 0x55, 0x37, 0x22, 0xc2, 0xd8, 0x8b, 0xa3, 0x67, 0xd9, 0x53, 0xb6, 0xb8, 0x5e,
	0xa7, 0x19, 0xe7, 0x90, 0x7b, 0xf3, 0x23, 0x88, 0x5d, 0x25, 0xd8, 0x89, 0xf2, 0x1d, 0x6e, 0x56,
	0x56, 0x34, 0x82, 0xbc, 0xe2, 0x07, 0x87, 0x05, 0xcc, 0x82, 0x13, 0x96, 0xb8, 0x16, 0x6c, 0x94,
	0xde, 0xf5, 0x3a, 0x7a, 0x2d, 0x77, 0xee, 0xd7, 0xd8, 0x86, 0x8d, 0x3b, 0xef, 0xac, 0xcb, 0x47,
	0xc8, 0x37, 0xf1, 0xbf, 0x61, 0x4b, 0xfe, 0x6f, 0xcb, 0xab, 0x82, 0xd9, 0x46, 0x58, 0xad, 0x88,
	0x1f, 0xf0, 0x19, 0x46, 0xeb, 0x40, 0x78, 0x57, 0x9d, 0xcf, 0x38, 0x85, 0x2e, 0x2e, 0xc8, 0x22,
	0x7b, 0xc9, 0xb0, 0x82, 0xc9, 0x97, 0x92, 0xf4, 0x41, 0x38, 0x1f, 0xfc, 0x21, 0x71, 0x71, 0xdb,
	0xd3, 0x14, 0xe0, 0xed, 0x61, 0x7b, 0x2f, 0x95, 0xff, 0x0e, 0xbb, 0xc8, 0xeb, 0x6d, 0xf0, 0x56,
	0x1d, 0x3f, 0x8d, 0xac, 0x63, 0x73, 0xbb, 0x49, 0xaa, 0x6c, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x21, 0xed, 0x2a, 0x3c, 0x48, 0x01, 0x00, 0x00,
}
